"""
plot_posterior_roc_pr_curves.py

Post-process posterior predictive probability draws generated by
latefusion_bcnn_posterior_metrics.py. For each posterior draw, this script
computes posterior ROC and precision-recall curves, plus patient-bootstrap
ROC and PR curves for the posterior-mean predictor. It saves pointwise 95%
credible bands and pointwise 95% bootstrap bands, along with AUROC/AUPRC
intervals.

Expected input NPZ keys:
    posterior_class1_probs: shape (n_draws, n_patients)
    labels:                 shape (n_patients,)

Example:
    python plot_posterior_roc_pr_curves.py \
        --results-dir latefusion_results \
        --split test \
        --show-samples 40
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from typing import Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import auc, precision_recall_curve, roc_auc_score, roc_curve


@dataclass
class PosteriorCurveResults:
    grid: np.ndarray
    sampled_curves: np.ndarray
    posterior_mean: np.ndarray
    posterior_median: np.ndarray
    lower_95: np.ndarray
    upper_95: np.ndarray
    posterior_mean_predictive_curve: np.ndarray
    area_draws: np.ndarray
    posterior_mean_predictive_area: float


@dataclass
class BootstrapCurveResults:
    observed_auc: float
    bootstrap_draws: np.ndarray
    bootstrap_mean: float
    bootstrap_median: float
    lower_95: float
    upper_95: float
    standard_error: float
    n_valid: int
    n_requested: int
    grid: np.ndarray
    curve_draws: np.ndarray
    curve_mean: np.ndarray
    curve_median: np.ndarray
    curve_lower_95: np.ndarray
    curve_upper_95: np.ndarray
    observed_curve: np.ndarray


def _validate_inputs(posterior_probs: np.ndarray, labels: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    posterior_probs = np.asarray(posterior_probs, dtype=np.float64)
    labels = np.asarray(labels, dtype=np.int64)

    if posterior_probs.ndim != 2:
        raise ValueError(
            "posterior_class1_probs must have shape (n_draws, n_patients); "
            f"received {posterior_probs.shape}."
        )
    if labels.ndim != 1:
        raise ValueError(f"labels must be one-dimensional; received {labels.shape}.")
    if posterior_probs.shape[1] != labels.shape[0]:
        raise ValueError(
            "The number of patients in posterior probabilities does not match labels: "
            f"{posterior_probs.shape[1]} vs {labels.shape[0]}."
        )
    if posterior_probs.shape[0] < 2:
        raise ValueError("At least two posterior draws are required for a credible interval.")
    if not np.all(np.isfinite(posterior_probs)):
        raise ValueError("posterior_class1_probs contains NaN or infinite values.")
    if np.any((posterior_probs < 0.0) | (posterior_probs > 1.0)):
        raise ValueError("Posterior probabilities must lie within [0, 1].")
    if not set(np.unique(labels)).issubset({0, 1}):
        raise ValueError("labels must contain only binary values 0 and 1.")
    if len(np.unique(labels)) != 2:
        raise ValueError("Both outcome classes must be present to calculate ROC and PR curves.")

    return posterior_probs, labels


def _summarize_curves(curves: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    return (
        curves.mean(axis=0),
        np.median(curves, axis=0),
        np.quantile(curves, 0.025, axis=0),
        np.quantile(curves, 0.975, axis=0),
    )


def calculate_posterior_roc_curves(
    posterior_probs: np.ndarray,
    labels: np.ndarray,
    grid_points: int = 501,
) -> PosteriorCurveResults:
    """Calculate posterior ROC curves on a shared false-positive-rate grid."""
    posterior_probs, labels = _validate_inputs(posterior_probs, labels)
    fpr_grid = np.linspace(0.0, 1.0, grid_points)
    interpolated_tprs = []
    auroc_draws = []

    for probs in posterior_probs:
        fpr, tpr, _ = roc_curve(labels, probs)
        interpolated_tpr = np.interp(fpr_grid, fpr, tpr)
        interpolated_tpr[0] = 0.0
        interpolated_tpr[-1] = 1.0
        interpolated_tprs.append(interpolated_tpr)
        auroc_draws.append(roc_auc_score(labels, probs))

    interpolated_tprs = np.asarray(interpolated_tprs, dtype=np.float64)
    auroc_draws = np.asarray(auroc_draws, dtype=np.float64)
    curve_mean, curve_median, lower_95, upper_95 = _summarize_curves(interpolated_tprs)

    mean_probs = posterior_probs.mean(axis=0)
    mean_fpr, mean_tpr, _ = roc_curve(labels, mean_probs)
    posterior_mean_predictive_tpr = np.interp(fpr_grid, mean_fpr, mean_tpr)
    posterior_mean_predictive_tpr[0] = 0.0
    posterior_mean_predictive_tpr[-1] = 1.0

    return PosteriorCurveResults(
        grid=fpr_grid,
        sampled_curves=interpolated_tprs,
        posterior_mean=curve_mean,
        posterior_median=curve_median,
        lower_95=lower_95,
        upper_95=upper_95,
        posterior_mean_predictive_curve=posterior_mean_predictive_tpr,
        area_draws=auroc_draws,
        posterior_mean_predictive_area=float(roc_auc_score(labels, mean_probs)),
    )


def _prepare_pr_for_interpolation(recall: np.ndarray, precision: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return increasing, unique recall values and one precision value per recall."""
    order = np.argsort(recall)
    recall_sorted = np.asarray(recall[order], dtype=np.float64)
    precision_sorted = np.asarray(precision[order], dtype=np.float64)

    unique_recall = np.unique(recall_sorted)
    # Repeated recall coordinates can occur. Taking the maximum precision gives
    # a stable upper-envelope representation at that exact recall coordinate.
    unique_precision = np.array(
        [precision_sorted[recall_sorted == value].max() for value in unique_recall],
        dtype=np.float64,
    )

    if unique_recall[0] > 0.0:
        unique_recall = np.insert(unique_recall, 0, 0.0)
        unique_precision = np.insert(unique_precision, 0, unique_precision[0])
    if unique_recall[-1] < 1.0:
        unique_recall = np.append(unique_recall, 1.0)
        unique_precision = np.append(unique_precision, unique_precision[-1])

    return unique_recall, unique_precision


def calculate_posterior_pr_curves(
    posterior_probs: np.ndarray,
    labels: np.ndarray,
    grid_points: int = 501,
) -> PosteriorCurveResults:
    """Calculate posterior PR curves on a shared recall grid."""
    posterior_probs, labels = _validate_inputs(posterior_probs, labels)
    recall_grid = np.linspace(0.0, 1.0, grid_points)
    interpolated_precisions = []
    auprc_draws = []

    for probs in posterior_probs:
        precision, recall, _ = precision_recall_curve(labels, probs)
        auprc_draws.append(auc(recall, precision))
        recall_unique, precision_unique = _prepare_pr_for_interpolation(recall, precision)
        interpolated_precision = np.interp(recall_grid, recall_unique, precision_unique)
        interpolated_precisions.append(interpolated_precision)

    interpolated_precisions = np.asarray(interpolated_precisions, dtype=np.float64)
    auprc_draws = np.asarray(auprc_draws, dtype=np.float64)
    curve_mean, curve_median, lower_95, upper_95 = _summarize_curves(interpolated_precisions)

    mean_probs = posterior_probs.mean(axis=0)
    mean_precision, mean_recall, _ = precision_recall_curve(labels, mean_probs)
    mean_recall_unique, mean_precision_unique = _prepare_pr_for_interpolation(
        mean_recall, mean_precision
    )
    posterior_mean_predictive_precision = np.interp(
        recall_grid, mean_recall_unique, mean_precision_unique
    )

    return PosteriorCurveResults(
        grid=recall_grid,
        sampled_curves=interpolated_precisions,
        posterior_mean=curve_mean,
        posterior_median=curve_median,
        lower_95=lower_95,
        upper_95=upper_95,
        posterior_mean_predictive_curve=posterior_mean_predictive_precision,
        area_draws=auprc_draws,
        posterior_mean_predictive_area=float(auc(mean_recall, mean_precision)),
    )


def _credible_interval(values: np.ndarray) -> tuple[float, float, float, float]:
    values = np.asarray(values, dtype=np.float64)
    return (
        float(values.mean()),
        float(np.median(values)),
        float(np.quantile(values, 0.025)),
        float(np.quantile(values, 0.975)),
    )


def bootstrap_posterior_mean_curves(
    posterior_probs: np.ndarray,
    labels: np.ndarray,
    n_bootstrap: int = 2000,
    grid_points: int = 501,
    random_seed: int = 42,
) -> tuple[BootstrapCurveResults, BootstrapCurveResults]:
    """Bootstrap patients for posterior-mean ROC and PR curves.

    Posterior probabilities are first averaged across Bayesian weight draws for
    each patient. Patients are then sampled with replacement. Each valid
    bootstrap replicate yields an ROC curve, a PR curve, AUROC, and AUPRC.
    Curves are interpolated onto shared grids so pointwise 95% bootstrap bands
    can be calculated.
    """
    posterior_probs, labels = _validate_inputs(posterior_probs, labels)
    if n_bootstrap < 2:
        raise ValueError("n_bootstrap must be at least 2.")
    if grid_points < 2:
        raise ValueError("grid_points must be at least 2.")

    mean_probs = posterior_probs.mean(axis=0)
    rng = np.random.default_rng(random_seed)
    n_patients = labels.shape[0]

    fpr_grid = np.linspace(0.0, 1.0, grid_points)
    recall_grid = np.linspace(0.0, 1.0, grid_points)
    roc_curves = []
    pr_curves = []
    auroc_draws = []
    auprc_draws = []

    for _ in range(n_bootstrap):
        indices = rng.integers(0, n_patients, size=n_patients)
        sampled_labels = labels[indices]
        sampled_probs = mean_probs[indices]
        if np.unique(sampled_labels).size < 2:
            continue

        fpr, tpr, _ = roc_curve(sampled_labels, sampled_probs)
        interp_tpr = np.interp(fpr_grid, fpr, tpr)
        interp_tpr[0] = 0.0
        interp_tpr[-1] = 1.0
        roc_curves.append(interp_tpr)
        auroc_draws.append(roc_auc_score(sampled_labels, sampled_probs))

        precision, recall, _ = precision_recall_curve(sampled_labels, sampled_probs)
        recall_unique, precision_unique = _prepare_pr_for_interpolation(recall, precision)
        interp_precision = np.interp(recall_grid, recall_unique, precision_unique)
        pr_curves.append(interp_precision)
        auprc_draws.append(auc(recall, precision))

    if len(auroc_draws) < 2:
        raise RuntimeError("Too few valid bootstrap replicates contained both classes.")

    roc_curves = np.asarray(roc_curves, dtype=np.float64)
    pr_curves = np.asarray(pr_curves, dtype=np.float64)
    auroc_draws = np.asarray(auroc_draws, dtype=np.float64)
    auprc_draws = np.asarray(auprc_draws, dtype=np.float64)

    mean_fpr, mean_tpr, _ = roc_curve(labels, mean_probs)
    observed_roc = np.interp(fpr_grid, mean_fpr, mean_tpr)
    observed_roc[0] = 0.0
    observed_roc[-1] = 1.0

    mean_precision, mean_recall, _ = precision_recall_curve(labels, mean_probs)
    recall_unique, precision_unique = _prepare_pr_for_interpolation(mean_recall, mean_precision)
    observed_pr = np.interp(recall_grid, recall_unique, precision_unique)

    roc_mean, roc_median, roc_lower, roc_upper = _summarize_curves(roc_curves)
    pr_mean, pr_median, pr_lower, pr_upper = _summarize_curves(pr_curves)

    roc_results = BootstrapCurveResults(
        observed_auc=float(roc_auc_score(labels, mean_probs)),
        bootstrap_draws=auroc_draws,
        bootstrap_mean=float(auroc_draws.mean()),
        bootstrap_median=float(np.median(auroc_draws)),
        lower_95=float(np.quantile(auroc_draws, 0.025)),
        upper_95=float(np.quantile(auroc_draws, 0.975)),
        standard_error=float(auroc_draws.std(ddof=1)),
        n_valid=int(auroc_draws.size),
        n_requested=int(n_bootstrap),
        grid=fpr_grid,
        curve_draws=roc_curves,
        curve_mean=roc_mean,
        curve_median=roc_median,
        curve_lower_95=roc_lower,
        curve_upper_95=roc_upper,
        observed_curve=observed_roc,
    )

    pr_results = BootstrapCurveResults(
        observed_auc=float(auc(mean_recall, mean_precision)),
        bootstrap_draws=auprc_draws,
        bootstrap_mean=float(auprc_draws.mean()),
        bootstrap_median=float(np.median(auprc_draws)),
        lower_95=float(np.quantile(auprc_draws, 0.025)),
        upper_95=float(np.quantile(auprc_draws, 0.975)),
        standard_error=float(auprc_draws.std(ddof=1)),
        n_valid=int(auprc_draws.size),
        n_requested=int(n_bootstrap),
        grid=recall_grid,
        curve_draws=pr_curves,
        curve_mean=pr_mean,
        curve_median=pr_median,
        curve_lower_95=pr_lower,
        curve_upper_95=pr_upper,
        observed_curve=observed_pr,
    )

    return roc_results, pr_results

def save_curve_tables(
    roc_results: PosteriorCurveResults,
    pr_results: PosteriorCurveResults,
    bootstrap_roc: BootstrapCurveResults,
    bootstrap_pr: BootstrapCurveResults,
    output_dir: str,
    split: str,
) -> None:
    roc_table = pd.DataFrame({
        "false_positive_rate": roc_results.grid,
        "posterior_curve_mean_tpr": roc_results.posterior_mean,
        "posterior_curve_median_tpr": roc_results.posterior_median,
        "lower_95_tpr": roc_results.lower_95,
        "upper_95_tpr": roc_results.upper_95,
        "posterior_mean_predictive_tpr": roc_results.posterior_mean_predictive_curve,
    })
    roc_table.to_csv(os.path.join(output_dir, f"{split}_posterior_roc_curve_band.csv"), index=False)

    pr_table = pd.DataFrame({
        "recall": pr_results.grid,
        "posterior_curve_mean_precision": pr_results.posterior_mean,
        "posterior_curve_median_precision": pr_results.posterior_median,
        "lower_95_precision": pr_results.lower_95,
        "upper_95_precision": pr_results.upper_95,
        "posterior_mean_predictive_precision": pr_results.posterior_mean_predictive_curve,
    })
    pr_table.to_csv(os.path.join(output_dir, f"{split}_posterior_pr_curve_band.csv"), index=False)

    bootstrap_roc_table = pd.DataFrame({
        "false_positive_rate": bootstrap_roc.grid,
        "bootstrap_curve_mean_tpr": bootstrap_roc.curve_mean,
        "bootstrap_curve_median_tpr": bootstrap_roc.curve_median,
        "bootstrap_lower_95_tpr": bootstrap_roc.curve_lower_95,
        "bootstrap_upper_95_tpr": bootstrap_roc.curve_upper_95,
        "posterior_mean_predictive_tpr": bootstrap_roc.observed_curve,
    })
    bootstrap_roc_table.to_csv(
        os.path.join(output_dir, f"{split}_posterior_mean_roc_bootstrap_band.csv"), index=False
    )

    bootstrap_pr_table = pd.DataFrame({
        "recall": bootstrap_pr.grid,
        "bootstrap_curve_mean_precision": bootstrap_pr.curve_mean,
        "bootstrap_curve_median_precision": bootstrap_pr.curve_median,
        "bootstrap_lower_95_precision": bootstrap_pr.curve_lower_95,
        "bootstrap_upper_95_precision": bootstrap_pr.curve_upper_95,
        "posterior_mean_predictive_precision": bootstrap_pr.observed_curve,
    })
    bootstrap_pr_table.to_csv(
        os.path.join(output_dir, f"{split}_posterior_mean_pr_bootstrap_band.csv"), index=False
    )

    roc_mean, roc_median, roc_lower, roc_upper = _credible_interval(roc_results.area_draws)
    pr_mean, pr_median, pr_lower, pr_upper = _credible_interval(pr_results.area_draws)
    area_summary = pd.DataFrame([
        {
            "metric": "auroc",
            "posterior_draw_mean": roc_mean,
            "posterior_draw_median": roc_median,
            "lower_95": roc_lower,
            "upper_95": roc_upper,
            "posterior_mean_predictive_value": roc_results.posterior_mean_predictive_area,
            "bootstrap_mean": bootstrap_roc.bootstrap_mean,
            "bootstrap_median": bootstrap_roc.bootstrap_median,
            "bootstrap_lower_95": bootstrap_roc.lower_95,
            "bootstrap_upper_95": bootstrap_roc.upper_95,
            "bootstrap_standard_error": bootstrap_roc.standard_error,
            "bootstrap_valid_replicates": bootstrap_roc.n_valid,
        },
        {
            "metric": "auprc",
            "posterior_draw_mean": pr_mean,
            "posterior_draw_median": pr_median,
            "lower_95": pr_lower,
            "upper_95": pr_upper,
            "posterior_mean_predictive_value": pr_results.posterior_mean_predictive_area,
            "bootstrap_mean": bootstrap_pr.bootstrap_mean,
            "bootstrap_median": bootstrap_pr.bootstrap_median,
            "bootstrap_lower_95": bootstrap_pr.lower_95,
            "bootstrap_upper_95": bootstrap_pr.upper_95,
            "bootstrap_standard_error": bootstrap_pr.standard_error,
            "bootstrap_valid_replicates": bootstrap_pr.n_valid,
        },
    ])
    area_summary.to_csv(
        os.path.join(output_dir, f"{split}_posterior_roc_pr_area_summary.csv"),
        index=False,
    )

    np.savez_compressed(
        os.path.join(output_dir, f"{split}_posterior_roc_pr_curve_samples.npz"),
        fpr_grid=roc_results.grid,
        posterior_tpr_draws=roc_results.sampled_curves,
        auroc_draws=roc_results.area_draws,
        recall_grid=pr_results.grid,
        posterior_precision_draws=pr_results.sampled_curves,
        auprc_draws=pr_results.area_draws,
        posterior_mean_auroc_bootstrap_draws=bootstrap_roc.bootstrap_draws,
        posterior_mean_auprc_bootstrap_draws=bootstrap_pr.bootstrap_draws,
        bootstrap_fpr_grid=bootstrap_roc.grid,
        posterior_mean_tpr_bootstrap_draws=bootstrap_roc.curve_draws,
        bootstrap_recall_grid=bootstrap_pr.grid,
        posterior_mean_precision_bootstrap_draws=bootstrap_pr.curve_draws,
    )


def plot_posterior_curves(
    roc_results: PosteriorCurveResults,
    pr_results: PosteriorCurveResults,
    bootstrap_roc: BootstrapCurveResults,
    bootstrap_pr: BootstrapCurveResults,
    labels: np.ndarray,
    output_dir: str,
    split: str,
    show_samples: int = 30,
    random_seed: int = 42,
) -> str:
    rng = np.random.default_rng(random_seed)
    n_draws = roc_results.sampled_curves.shape[0]
    n_show = min(max(show_samples, 0), n_draws)
    selected = rng.choice(n_draws, size=n_show, replace=False) if n_show else np.array([], dtype=int)

    roc_mean, _, roc_lower, roc_upper = _credible_interval(roc_results.area_draws)
    pr_mean, _, pr_lower, pr_upper = _credible_interval(pr_results.area_draws)
    prevalence = float(np.mean(labels))

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

    for draw_index in selected:
        axes[0].plot(
            roc_results.grid,
            roc_results.sampled_curves[draw_index],
            linewidth=0.6,
            alpha=0.10,
        )
    axes[0].fill_between(
        roc_results.grid,
        roc_results.lower_95,
        roc_results.upper_95,
        alpha=0.25,
        label="Pointwise 95% credible interval",
    )
    axes[0].plot(
        roc_results.grid,
        roc_results.posterior_mean,
        linewidth=2.2,
        label=f"Mean posterior curve (AUROC {roc_mean:.3f}; 95% CrI {roc_lower:.3f}-{roc_upper:.3f})",
    )
    axes[0].fill_between(
        bootstrap_roc.grid,
        bootstrap_roc.curve_lower_95,
        bootstrap_roc.curve_upper_95,
        alpha=0.16,
        label="Posterior-mean ROC patient-bootstrap 95% band",
    )
    axes[0].plot(
        roc_results.grid,
        roc_results.posterior_mean_predictive_curve,
        linewidth=1.6,
        linestyle="--",
        label=(
            f"Posterior-mean predictor (AUROC {roc_results.posterior_mean_predictive_area:.3f}; "
            f"bootstrap 95% CI {bootstrap_roc.lower_95:.3f}-{bootstrap_roc.upper_95:.3f})"
        ),
    )
    axes[0].plot([0.0, 1.0], [0.0, 1.0], linestyle=":", linewidth=1.2, label="Chance")
    axes[0].set_xlim(0.0, 1.0)
    axes[0].set_ylim(0.0, 1.0)
    axes[0].set_xlabel("False Positive Rate")
    axes[0].set_ylabel("True Positive Rate")
    axes[0].set_title(f"{split.capitalize()} Posterior ROC Curves")
    axes[0].legend(loc="lower right", fontsize=8)
    axes[0].grid(alpha=0.25)

    for draw_index in selected:
        axes[1].plot(
            pr_results.grid,
            pr_results.sampled_curves[draw_index],
            linewidth=0.6,
            alpha=0.10,
        )
    axes[1].fill_between(
        pr_results.grid,
        pr_results.lower_95,
        pr_results.upper_95,
        alpha=0.25,
        label="Pointwise 95% credible interval",
    )
    axes[1].plot(
        pr_results.grid,
        pr_results.posterior_mean,
        linewidth=2.2,
        label=f"Mean posterior curve (AUPRC {pr_mean:.3f}; 95% CrI {pr_lower:.3f}-{pr_upper:.3f})",
    )
    axes[1].fill_between(
        bootstrap_pr.grid,
        bootstrap_pr.curve_lower_95,
        bootstrap_pr.curve_upper_95,
        alpha=0.16,
        label="Posterior-mean PR patient-bootstrap 95% band",
    )
    axes[1].plot(
        pr_results.grid,
        pr_results.posterior_mean_predictive_curve,
        linewidth=1.6,
        linestyle="--",
        label=(
            f"Posterior-mean predictor (AUPRC {pr_results.posterior_mean_predictive_area:.3f}; "
            f"bootstrap 95% CI {bootstrap_pr.lower_95:.3f}-{bootstrap_pr.upper_95:.3f})"
        ),
    )
    axes[1].axhline(prevalence, linestyle=":", linewidth=1.2, label=f"Prevalence ({prevalence:.3f})")
    axes[1].set_xlim(0.0, 1.0)
    axes[1].set_ylim(0.0, 1.0)
    axes[1].set_xlabel("Recall")
    axes[1].set_ylabel("Precision")
    axes[1].set_title(f"{split.capitalize()} Posterior Precision-Recall Curves")
    axes[1].legend(loc="lower left", fontsize=8)
    axes[1].grid(alpha=0.25)

    fig.suptitle(
        f"Posterior Curve Samples and Pointwise 95% Credible Bands ({n_draws} draws)",
        fontsize=13,
    )
    fig.tight_layout()
    output_path = os.path.join(output_dir, f"{split}_posterior_roc_pr_credible_intervals.png")
    fig.savefig(output_path, dpi=180, bbox_inches="tight")
    plt.close(fig)
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot posterior ROC and PR curves with pointwise 95% credible intervals."
    )
    parser.add_argument(
        "--results-dir",
        default="latefusion_results",
        help="Directory containing <split>_posterior_predictive.npz.",
    )
    parser.add_argument(
        "--split",
        default="test",
        help="Dataset split name used in the NPZ filename, such as test or train.",
    )
    parser.add_argument(
        "--input-npz",
        default=None,
        help="Optional explicit posterior predictive NPZ path.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Optional output directory. Defaults to --results-dir.",
    )
    parser.add_argument(
        "--grid-points",
        type=int,
        default=501,
        help="Number of shared interpolation points for each curve.",
    )
    parser.add_argument(
        "--show-samples",
        type=int,
        default=30,
        help="Number of individual posterior curves to draw faintly behind the interval.",
    )
    parser.add_argument(
        "--bootstrap-samples",
        type=int,
        default=2000,
        help="Number of patient bootstrap replicates for posterior-mean ROC and PR curves.",
    )
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = args.input_npz or os.path.join(
        args.results_dir, f"{args.split}_posterior_predictive.npz"
    )
    output_dir = args.output_dir or args.results_dir
    os.makedirs(output_dir, exist_ok=True)

    if not os.path.exists(input_path):
        raise FileNotFoundError(
            f"Posterior predictive file not found: {input_path}. "
            "Run latefusion_bcnn_posterior_metrics.py first."
        )
    if args.grid_points < 2:
        raise ValueError("--grid-points must be at least 2.")

    with np.load(input_path) as data:
        required = {"posterior_class1_probs", "labels"}
        missing = required.difference(data.files)
        if missing:
            raise KeyError(f"Input NPZ is missing required keys: {sorted(missing)}")
        posterior_probs = data["posterior_class1_probs"]
        labels = data["labels"]

    posterior_probs, labels = _validate_inputs(posterior_probs, labels)
    roc_results = calculate_posterior_roc_curves(
        posterior_probs, labels, grid_points=args.grid_points
    )
    pr_results = calculate_posterior_pr_curves(
        posterior_probs, labels, grid_points=args.grid_points
    )
    bootstrap_roc, bootstrap_pr = bootstrap_posterior_mean_curves(
        posterior_probs,
        labels,
        n_bootstrap=args.bootstrap_samples,
        grid_points=args.grid_points,
        random_seed=args.seed,
    )

    save_curve_tables(roc_results, pr_results, bootstrap_roc, bootstrap_pr, output_dir, args.split)
    plot_path = plot_posterior_curves(
        roc_results,
        pr_results,
        bootstrap_roc,
        bootstrap_pr,
        labels,
        output_dir,
        args.split,
        show_samples=args.show_samples,
        random_seed=args.seed,
    )

    roc_mean, _, roc_lower, roc_upper = _credible_interval(roc_results.area_draws)
    pr_mean, _, pr_lower, pr_upper = _credible_interval(pr_results.area_draws)
    print(
        f"AUROC posterior draws: mean={roc_mean:.6f}, 95% CrI=[{roc_lower:.6f}, {roc_upper:.6f}]",
        flush=True,
    )
    print(
        f"AUPRC posterior draws: mean={pr_mean:.6f}, 95% CrI=[{pr_lower:.6f}, {pr_upper:.6f}]",
        flush=True,
    )
    print(
        "Posterior-mean AUROC patient bootstrap: "
        f"observed={bootstrap_roc.observed_auc:.6f}, "
        f"95% CI=[{bootstrap_roc.lower_95:.6f}, {bootstrap_roc.upper_95:.6f}], "
        f"SE={bootstrap_roc.standard_error:.6f}, "
        f"valid={bootstrap_roc.n_valid}/{bootstrap_roc.n_requested}",
        flush=True,
    )
    print(
        "Posterior-mean AUPRC patient bootstrap: "
        f"observed={bootstrap_pr.observed_auc:.6f}, "
        f"95% CI=[{bootstrap_pr.lower_95:.6f}, {bootstrap_pr.upper_95:.6f}], "
        f"SE={bootstrap_pr.standard_error:.6f}, "
        f"valid={bootstrap_pr.n_valid}/{bootstrap_pr.n_requested}",
        flush=True,
    )
    print(f"Saved posterior ROC/PR plot: {plot_path}", flush=True)
    print(f"Saved curve tables and raw interpolated draws to: {output_dir}", flush=True)


if __name__ == "__main__":
    main()
